import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { Empresa } from "@/lib/empresa";
import { DEFAULT_BRAND_THEME, type ModoFundo } from "@/lib/theme";

/** Hard gate for the Master SaaS panel — true only for the ecosystem owner. */
export function useIsSuperAdmin(userId: string | undefined) {
  return useQuery({
    queryKey: ["is-super-admin", userId],
    enabled: !!userId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("user_roles")
        .select("role")
        .eq("user_id", userId!)
        .eq("role", "super_admin")
        .maybeSingle();
      if (error) throw error;
      return !!data;
    },
  });
}

export interface EmpresaRow extends Empresa {
  created_at: string;
}

/** Lists every company in the ecosystem (super_admin only, enforced by a
 *  role-guarded database function — sensitive columns never hit the Data API). */
export async function listAllEmpresas(): Promise<EmpresaRow[]> {
  const { data, error } = await supabase.rpc("admin_list_empresas");
  if (error) throw error;
  return (data ?? []).map((d) => ({
    id: d.id,
    nome_fantasia: d.nome_fantasia ?? "",
    logotipo_url: d.logotipo_url ?? "/logo.png",
    taxa_servico_mesa: Number(d.taxa_servico_mesa ?? 0),
    taxa_entrega_valor: Number((d as { taxa_entrega_valor?: number }).taxa_entrega_valor ?? 0),

    dominio_customizado: d.dominio_customizado ?? null,
    subdominio: (d as { subdominio?: string | null }).subdominio ?? null,
    cnpj: d.cnpj ?? "",
    inscricao_estadual: d.inscricao_estadual ?? "",
    regime_tributario: d.regime_tributario ?? "simples_nacional",
    cep: d.cep ?? "",
    logradouro: d.logradouro ?? "",
    numero: d.numero ?? "",
    complemento: d.complemento ?? "",
    bairro: d.bairro ?? "",
    cidade: d.cidade ?? "",
    estado: d.estado ?? "",
    ativo: d.ativo ?? true,
    cor_primaria: d.cor_primaria ?? DEFAULT_BRAND_THEME.cor_primaria,
    cor_secundaria: d.cor_secundaria ?? DEFAULT_BRAND_THEME.cor_secundaria,
    modo_fundo: (d.modo_fundo as ModoFundo) ?? DEFAULT_BRAND_THEME.modo_fundo,
    percentual_cashback: Number(d.percentual_cashback ?? 5),
    cashback_ativo: d.cashback_ativo ?? true,
    monitor_cozinha: false,
    monitor_bar: false,
    monitor_pizzaria: false,
    ai_report_model: d.ai_report_model ?? "openai/gpt-5.5",
    markup_ifood_percentual: Number((d as { markup_ifood_percentual?: number | null }).markup_ifood_percentual ?? 0),
    created_at: d.created_at,
  }));
}

export interface NovaEmpresa {
  nome_fantasia: string;
  dominio_customizado: string | null;
  ativo: boolean;
  cep: string;
  logradouro: string;
  numero: string;
  complemento: string;
  bairro: string;
  cidade: string;
  estado: string;
}

/**
 * Creates a brand-new tenant company. A fresh empresa_id is generated by the
 * database, ready to receive that restaurant's isolated products/categories.
 */
export async function createEmpresa(input: NovaEmpresa): Promise<string> {
  const { data, error } = await supabase
    .from("empresas")
    .insert({
      nome_fantasia: input.nome_fantasia.trim(),
      dominio_customizado: input.dominio_customizado?.trim() || null,
      ativo: input.ativo,
      logotipo_url: "/logo.png",
      taxa_servico_mesa: 0,
      cep: input.cep.trim(),
      logradouro: input.logradouro.trim(),
      numero: input.numero.trim(),
      complemento: input.complemento.trim(),
      bairro: input.bairro.trim(),
      cidade: input.cidade.trim(),
      estado: input.estado.trim(),
    })
    .select("id")
    .single();
  if (error) throw error;
  return data.id;
}
