import { useEffect, useRef } from "react";

/**
 * Global back-button manager for modals / sheets (native-app UX).
 *
 * Goal: when a modal/sheet is open and the user triggers the hardware/browser
 * back button (or the Android/iOS back gesture), we close the top-most overlay
 * instead of navigating the whole PWA away.
 *
 * Implementation notes:
 * - A single synthetic history entry is pushed per open overlay, so nested
 *   overlays close one-at-a-time (LIFO) with successive back presses.
 * - A shared `popstate` listener consumes the back event and closes the top
 *   overlay. It is installed once and never navigates the real route.
 * - Closing through our own UI (top "Voltar" button, overlay click, Esc, save)
 *   pops the synthetic entry via `history.back()` to keep the stack balanced.
 *   That programmatic back fires a `popstate` we deliberately ignore, so it
 *   never double-closes the next overlay in the stack.
 */

interface ModalEntry {
  id: string;
  close: () => void;
}

const stack: ModalEntry[] = [];
let listening = false;
// Number of upcoming `popstate` events generated by our own history.back()
// calls that must be ignored (not treated as a user back gesture).
let ignoreCount = 0;

function ensureListener() {
  if (listening || typeof window === "undefined") return;
  listening = true;
  window.addEventListener("popstate", () => {
    if (ignoreCount > 0) {
      ignoreCount -= 1;
      return;
    }
    // Genuine user back gesture: close the top overlay.
    const top = stack.pop();
    if (top) top.close();
  });
}

function openModal(entry: ModalEntry) {
  ensureListener();
  // Idempotent: ignore duplicate registrations (double render / HMR).
  if (stack.some((e) => e.id === entry.id)) return;
  stack.push(entry);
  window.history.pushState({ __modal: entry.id }, "", window.location.href);
}

function closeModal(id: string) {
  const idx = stack.findIndex((e) => e.id === id);
  // Already removed by a popstate (hardware back) — nothing to unwind.
  if (idx === -1) return;
  stack.splice(idx, 1);
  // Pop the synthetic entry we added; ignore the resulting popstate.
  ignoreCount += 1;
  window.history.back();
}

let counter = 0;

/**
 * Wire an overlay's open state to the hardware back button.
 * @param open   whether the overlay is currently open
 * @param onClose callback that closes the overlay (e.g. setOpen(false))
 */
export function useModalHistoryGuard(open: boolean, onClose: () => void) {
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;

  const idRef = useRef<string>("");
  if (!idRef.current) idRef.current = `modal-${++counter}`;

  useEffect(() => {
    if (typeof window === "undefined" || !open) return;
    const id = idRef.current;
    openModal({ id, close: () => onCloseRef.current() });
    return () => closeModal(id);
  }, [open]);
}
