import { useEffect, useRef } from "react";
import { useRouter } from "@tanstack/react-router";
import type { RouterHistory } from "@tanstack/history";

/**
 * Native-app back-button behaviour for modals / sheets.
 *
 * When an overlay opens we push ONE synthetic history entry through the
 * router's own history object (raw `window.history` calls desync TanStack
 * Router and cause phantom navigations). If the user triggers the hardware /
 * browser back button (or the Android/iOS back gesture) the router emits a
 * `BACK` action; we consume it and close the top-most overlay instead of
 * navigating the PWA away.
 *
 * Nested overlays each push an entry, so successive back presses close them
 * one-at-a-time (LIFO). Closing through our own UI (top "Voltar" button,
 * overlay click, Esc, save) pops the synthetic entry via `history.back()` to
 * keep the navigation stack perfectly balanced; that programmatic back is
 * flagged so it never double-closes the next overlay.
 */

interface ModalEntry {
  id: string;
  close: () => void;
}

const stack: ModalEntry[] = [];
let unsubscribe: (() => void) | null = null;
// Number of upcoming BACK actions generated by our own history.back() calls
// that must be ignored (not treated as a user back gesture).
let ignoreCount = 0;

function ensureSubscription(history: RouterHistory) {
  if (unsubscribe) return;
  unsubscribe = history.subscribe(({ action }) => {
    if (action.type !== "BACK") return;
    if (ignoreCount > 0) {
      ignoreCount -= 1;
      return;
    }
    const top = stack.pop();
    if (top) top.close();
  });
}

function openModal(history: RouterHistory, entry: ModalEntry) {
  ensureSubscription(history);
  // Idempotent: ignore duplicate registrations (double render / HMR).
  if (stack.some((e) => e.id === entry.id)) return;
  stack.push(entry);
  const prevState = (history.location.state ?? {}) as unknown as Record<
    string,
    unknown
  >;
  // Push the SAME location so the route/component stays mounted; only a
  // synthetic entry is added for the back gesture to consume.
  history.push(history.location.href, { ...prevState, __modal: entry.id });
}

function closeModal(history: RouterHistory, id: string) {
  const idx = stack.findIndex((e) => e.id === id);
  // Already removed by a BACK action (hardware back) — nothing to unwind.
  if (idx === -1) return;
  stack.splice(idx, 1);
  ignoreCount += 1;
  history.back();
}

let counter = 0;

/**
 * Wire an overlay's open state to the hardware back button.
 * @param open    whether the overlay is currently open
 * @param onClose callback that closes the overlay (e.g. setOpen(false))
 */
export function useModalHistoryGuard(open: boolean, onClose: () => void) {
  const router = useRouter();
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;

  const idRef = useRef<string>("");
  if (!idRef.current) idRef.current = `modal-${++counter}`;

  useEffect(() => {
    if (!open) return;
    const history = router.history;
    const id = idRef.current;
    openModal(history, { id, close: () => onCloseRef.current() });
    return () => closeModal(history, id);
  }, [open, router]);
}
