import { useEffect, useRef } from "react";

/**
 * Native-app back-button behaviour for modals / sheets.
 *
 * When an overlay opens we push ONE synthetic history entry. If the user
 * triggers the hardware/browser back button (or the Android/iOS back gesture)
 * the `popstate` fires, we consume it and close the top-most overlay instead
 * of ejecting the user out of the PWA. The URL is kept identical, so the
 * router never sees a route change.
 *
 * Nested overlays each push an entry, so successive back presses close them
 * one-at-a-time (LIFO). Closing through our own UI (top "Voltar" button,
 * overlay click, Esc, save) pops the synthetic entry via `history.back()` to
 * keep the stack balanced; that programmatic back is flagged so it never
 * double-closes the next overlay.
 */

interface ModalEntry {
  id: string;
  close: () => void;
}

const stack: ModalEntry[] = [];
let listening = false;
// Upcoming popstate events generated by our own history.back() that must be
// ignored (not treated as a user back gesture).
let ignoreCount = 0;

function handlePopState() {
  if (ignoreCount > 0) {
    ignoreCount -= 1;
    return;
  }
  const top = stack.pop();
  if (top) top.close();
}

function ensureListener() {
  if (listening || typeof window === "undefined") return;
  listening = true;
  window.addEventListener("popstate", handlePopState);
}

function openModal(entry: ModalEntry) {
  ensureListener();
  // Idempotent: ignore duplicate registrations (double render / HMR).
  if (stack.some((e) => e.id === entry.id)) return;
  stack.push(entry);
  // Preserve any existing history state (e.g. the router's scroll key) and keep
  // the exact same URL so no route change is triggered.
  const prevState =
    (window.history.state as Record<string, unknown> | null) ?? {};
  window.history.pushState(
    { ...prevState, __modal: entry.id },
    "",
    window.location.href,
  );
}

function closeModal(id: string) {
  const idx = stack.findIndex((e) => e.id === id);
  // Already removed by a popstate (hardware back) — nothing to unwind.
  if (idx === -1) return;
  stack.splice(idx, 1);
  ignoreCount += 1;
  window.history.back();
}

let counter = 0;

/**
 * Wire an overlay's open state to the hardware back button.
 * @param open    whether the overlay is currently open
 * @param onClose callback that closes the overlay (e.g. setOpen(false))
 */
export function useModalHistoryGuard(open: boolean, onClose: () => void) {
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;

  const idRef = useRef<string>("");
  if (!idRef.current) idRef.current = `modal-${++counter}`;

  useEffect(() => {
    if (typeof window === "undefined" || !open) return;
    const id = idRef.current;
    openModal({ id, close: () => onCloseRef.current() });
    return () => closeModal(id);
  }, [open]);
}
