/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MinhaComandaRouteImport } from './routes/minha-comanda'
import { Route as MesaRouteImport } from './routes/mesa'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth_.update-password'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedHomeNetflixRouteImport } from './routes/_authenticated/home-netflix'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTapReconcileRouteImport } from './routes/api/public/tap/reconcile'
import { Route as ApiPublicTapPixCreateRouteImport } from './routes/api/public/tap/pix/create'
import { Route as ApiPublicTapCardSettleRouteImport } from './routes/api/public/tap/card/settle'
import { Route as ApiPublicTapCardRefundRouteImport } from './routes/api/public/tap/card/refund'
import { Route as ApiPublicTapPixWebhookProviderRouteImport } from './routes/api/public/tap/pix/webhook.$provider'
import { Route as ApiPublicTapPixStatusIdRouteImport } from './routes/api/public/tap/pix/status.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaComandaRoute = MinhaComandaRouteImport.update({
  id: '/minha-comanda',
  path: '/minha-comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaRoute = MesaRouteImport.update({
  id: '/mesa',
  path: '/mesa',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth_/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeNetflixRoute =
  AuthenticatedHomeNetflixRouteImport.update({
    id: '/home-netflix',
    path: '/home-netflix',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTapReconcileRoute = ApiPublicTapReconcileRouteImport.update({
  id: '/api/public/tap/reconcile',
  path: '/api/public/tap/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTapPixCreateRoute = ApiPublicTapPixCreateRouteImport.update({
  id: '/api/public/tap/pix/create',
  path: '/api/public/tap/pix/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTapCardSettleRoute = ApiPublicTapCardSettleRouteImport.update({
  id: '/api/public/tap/card/settle',
  path: '/api/public/tap/card/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTapCardRefundRoute = ApiPublicTapCardRefundRouteImport.update({
  id: '/api/public/tap/card/refund',
  path: '/api/public/tap/card/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTapPixWebhookProviderRoute =
  ApiPublicTapPixWebhookProviderRouteImport.update({
    id: '/api/public/tap/pix/webhook/$provider',
    path: '/api/public/tap/pix/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTapPixStatusIdRoute = ApiPublicTapPixStatusIdRouteImport.update({
  id: '/api/public/tap/pix/status/$id',
  path: '/api/public/tap/pix/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/mesa': typeof MesaRoute
  '/minha-comanda': typeof MinhaComandaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/home-netflix': typeof AuthenticatedHomeNetflixRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/api/public/tap/reconcile': typeof ApiPublicTapReconcileRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/tap/card/refund': typeof ApiPublicTapCardRefundRoute
  '/api/public/tap/card/settle': typeof ApiPublicTapCardSettleRoute
  '/api/public/tap/pix/create': typeof ApiPublicTapPixCreateRoute
  '/api/public/tap/pix/status/$id': typeof ApiPublicTapPixStatusIdRoute
  '/api/public/tap/pix/webhook/$provider': typeof ApiPublicTapPixWebhookProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/mesa': typeof MesaRoute
  '/minha-comanda': typeof MinhaComandaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/home-netflix': typeof AuthenticatedHomeNetflixRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/api/public/tap/reconcile': typeof ApiPublicTapReconcileRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/tap/card/refund': typeof ApiPublicTapCardRefundRoute
  '/api/public/tap/card/settle': typeof ApiPublicTapCardSettleRoute
  '/api/public/tap/pix/create': typeof ApiPublicTapPixCreateRoute
  '/api/public/tap/pix/status/$id': typeof ApiPublicTapPixStatusIdRoute
  '/api/public/tap/pix/webhook/$provider': typeof ApiPublicTapPixWebhookProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/mesa': typeof MesaRoute
  '/minha-comanda': typeof MinhaComandaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/home-netflix': typeof AuthenticatedHomeNetflixRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/auth_/update-password': typeof AuthUpdatePasswordRoute
  '/api/public/tap/reconcile': typeof ApiPublicTapReconcileRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/tap/card/refund': typeof ApiPublicTapCardRefundRoute
  '/api/public/tap/card/settle': typeof ApiPublicTapCardSettleRoute
  '/api/public/tap/pix/create': typeof ApiPublicTapPixCreateRoute
  '/api/public/tap/pix/status/$id': typeof ApiPublicTapPixStatusIdRoute
  '/api/public/tap/pix/webhook/$provider': typeof ApiPublicTapPixWebhookProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/mesa'
    | '/minha-comanda'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/caixa'
    | '/home-netflix'
    | '/menu'
    | '/orders'
    | '/perfil'
    | '/superadmin'
    | '/auth/update-password'
    | '/api/public/tap/reconcile'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/tap/card/refund'
    | '/api/public/tap/card/settle'
    | '/api/public/tap/pix/create'
    | '/api/public/tap/pix/status/$id'
    | '/api/public/tap/pix/webhook/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/mesa'
    | '/minha-comanda'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/caixa'
    | '/home-netflix'
    | '/menu'
    | '/orders'
    | '/perfil'
    | '/superadmin'
    | '/auth/update-password'
    | '/api/public/tap/reconcile'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/tap/card/refund'
    | '/api/public/tap/card/settle'
    | '/api/public/tap/pix/create'
    | '/api/public/tap/pix/status/$id'
    | '/api/public/tap/pix/webhook/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/mesa'
    | '/minha-comanda'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/caixa'
    | '/_authenticated/home-netflix'
    | '/_authenticated/menu'
    | '/_authenticated/orders'
    | '/_authenticated/perfil'
    | '/_authenticated/superadmin'
    | '/auth_/update-password'
    | '/api/public/tap/reconcile'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/tap/card/refund'
    | '/api/public/tap/card/settle'
    | '/api/public/tap/pix/create'
    | '/api/public/tap/pix/status/$id'
    | '/api/public/tap/pix/webhook/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  MesaRoute: typeof MesaRoute
  MinhaComandaRoute: typeof MinhaComandaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  ApiPublicTapReconcileRoute: typeof ApiPublicTapReconcileRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicTapCardRefundRoute: typeof ApiPublicTapCardRefundRoute
  ApiPublicTapCardSettleRoute: typeof ApiPublicTapCardSettleRoute
  ApiPublicTapPixCreateRoute: typeof ApiPublicTapPixCreateRoute
  ApiPublicTapPixStatusIdRoute: typeof ApiPublicTapPixStatusIdRoute
  ApiPublicTapPixWebhookProviderRoute: typeof ApiPublicTapPixWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-comanda': {
      id: '/minha-comanda'
      path: '/minha-comanda'
      fullPath: '/minha-comanda'
      preLoaderRoute: typeof MinhaComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa': {
      id: '/mesa'
      path: '/mesa'
      fullPath: '/mesa'
      preLoaderRoute: typeof MesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/update-password': {
      id: '/auth_/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home-netflix': {
      id: '/_authenticated/home-netflix'
      path: '/home-netflix'
      fullPath: '/home-netflix'
      preLoaderRoute: typeof AuthenticatedHomeNetflixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tap/reconcile': {
      id: '/api/public/tap/reconcile'
      path: '/api/public/tap/reconcile'
      fullPath: '/api/public/tap/reconcile'
      preLoaderRoute: typeof ApiPublicTapReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tap/pix/create': {
      id: '/api/public/tap/pix/create'
      path: '/api/public/tap/pix/create'
      fullPath: '/api/public/tap/pix/create'
      preLoaderRoute: typeof ApiPublicTapPixCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tap/card/settle': {
      id: '/api/public/tap/card/settle'
      path: '/api/public/tap/card/settle'
      fullPath: '/api/public/tap/card/settle'
      preLoaderRoute: typeof ApiPublicTapCardSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tap/card/refund': {
      id: '/api/public/tap/card/refund'
      path: '/api/public/tap/card/refund'
      fullPath: '/api/public/tap/card/refund'
      preLoaderRoute: typeof ApiPublicTapCardRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tap/pix/webhook/$provider': {
      id: '/api/public/tap/pix/webhook/$provider'
      path: '/api/public/tap/pix/webhook/$provider'
      fullPath: '/api/public/tap/pix/webhook/$provider'
      preLoaderRoute: typeof ApiPublicTapPixWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tap/pix/status/$id': {
      id: '/api/public/tap/pix/status/$id'
      path: '/api/public/tap/pix/status/$id'
      fullPath: '/api/public/tap/pix/status/$id'
      preLoaderRoute: typeof ApiPublicTapPixStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedHomeNetflixRoute: typeof AuthenticatedHomeNetflixRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedHomeNetflixRoute: AuthenticatedHomeNetflixRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  MesaRoute: MesaRoute,
  MinhaComandaRoute: MinhaComandaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  ApiPublicTapReconcileRoute: ApiPublicTapReconcileRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicTapCardRefundRoute: ApiPublicTapCardRefundRoute,
  ApiPublicTapCardSettleRoute: ApiPublicTapCardSettleRoute,
  ApiPublicTapPixCreateRoute: ApiPublicTapPixCreateRoute,
  ApiPublicTapPixStatusIdRoute: ApiPublicTapPixStatusIdRoute,
  ApiPublicTapPixWebhookProviderRoute: ApiPublicTapPixWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
